=== DynasoftBr/Poseidon/src/api/v1/entities/schemas/entity-type-schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema",
    "type": "object",
    "properties": {
        "_id": {
            "$ref": "./definitions/id-def.json"
        },
        "name": {
            "$ref": "./definitions/name-def.json"
        },
        "label": {
            "$ref": "./definitions/label-def.json"
        },
        "properties": {
            "type": "array",
            "items": {
                "minItems": 1,
                "$ref": "property-schema.json"
            }
        }
    },
    "required": [
        "_id",
        "name",
        "properties"
    ]
}

=== DynasoftBr/Poseidon/src/api/v1/entities/entity-ref.json
{
    "_id": "entity_ref",
    "name": "entity_ref",
    "label": "Ref",
    "properties": [
        {
            "name": "entity",
            "label": "Entity",
            "type": "linkedEntity",
            "ref": {
                "entity": {
                    "id": "entity_type",
                    "label": "Entity Type"
                }
            }
        }
    ]
}

=== DynasoftBr/Poseidon/src/api/v1/entities/property.json
{
    "$schema": "./schemas/entity-type-schema.json",
    "_id": "property",
    "name": "property",
    "label": "Property",
    "properties": [
        {
            "name": "name",
            "label": "Name",
            "validation": {
                "type": "string",
                "pattern": "",
                "max": 50,
                "min": 2
            }
        },
        {
            "name": "type",
            "label": "Type",
            "validation": {
                "type": "string",
                "enum": [
                    "string",
                    "integer",
                    "number",
                    "date",
                    "boolean",
                    "abstractEntity",
                    "linkedEntity",
                    "array"
                ]
            }
        },
        {
            "name": "min",
            "label": "Minumum",
            "validation": {
                "type": "number"
            }
        },
        {
            "name": "max",
            "label": "Minumum",
            "validation": {
                "type": "number"
            }
        },
        {
            "name": "pattern",
            "label": "Pattern",
            "validation": {
                "type": "string"
            }
        },
        {
            "name": "ref",
            "label": "Ref",
            "validation": {
                "type": "linkedEntity",
                "ref": {
                    "id": "entity_type",
                    "label": "Entity type"
                },
                "linkedProperties": [
                    {
                        "name": "id",
                        "label": "Id",
                        "keepUpToDate": true
                    },
                    {
                        "name": "label",
                        "label": "Label",
                        "keepUpToDate": true
                    }
                ]
            }
        },
        {
            "name": "items",
            "validation": {
                "type": "abstractEntity",
                "ref": {
                    "id": "validation",
                    "label": "Validation"
                }
            }
        },
        {
            "name": "linkedProperties",
            "validation": {
                "type": "array",
                "items": {
                    "type": "abstractEntity",
                    "ref": {
                        "id": "linkedProperties",
                        "label": "Linked Properties"
                    }
                }
            }
        }
    ]
}

=== DynasoftBr/Poseidon/src/api/v1/entities/entity-type.json
{
    "$schema": "./schemas/entity-type-schema.json",
    "_id": "entity_type",
    "name": "entity_type",
    "label": "Entity Type",
    "properties": [
        {
            "name": "_id",
            "label": "Id",
            "type": "string",
            "min": 1,
            "max": 32
        },
        {
            "name": "name",
            "label": "Name",
            "type": "string",
            "pattern": "/[^\\s]/g",
            "max": 50,
            "min": 2
        },
        {
            "name": "label",
            "label": "Label",
            "type": "string",
            "max": 50
        },
        {
            "name": "properties",
            "label": "Properties",
            "type": "array",
            "items": [
                {
                    "type": "abstractEntity",
                    "ref": {
                        "id": "property",
                        "label": "Property"
                    }
                }
            ]
        }
    ]
}
